# Generated by Django 3.2.16 on 2022-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='Volunteer', max_length=30),
        ),
    ]
