# Generated by Django 3.2.16 on 2022-12-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0007_auto_20221214_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Picture',
        ),
    ]
