# Generated by Django 3.2.16 on 2022-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0008_rename_gallery_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.IntegerField(choices=[(0, 'Real Time'), (1, 'Archive')], default=0),
        ),
    ]
