# Generated by Django 3.2.16 on 2023-01-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0009_auto_20221221_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='alt',
            field=models.TextField(default='Release Eritrea gallery picture'),
        ),
    ]
